spring:
  application:
    name: server
  datasource:
    url : jdbc:mysql://localhost:3306/chat
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8083
logging:
  level:
    root: debug

