version: '3.8'

services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8083
    depends_on:
      - server
    networks:
      - chat-network

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/chat?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    networks:
      - chat-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=chat
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mysql-data: 